### PR TITLE
Vectors:Atomic vectors

### PR DESCRIPTION
**Pull request by lindbrook**
Wildcards for is.*() or as.*() functions?

### CODE REVIEW

**Comment by lindbrook** [comment]
asterik didn't print: "is.*()" etc.

**Comment by hadley** [comment]
`is.*()` I think. In other places I use (e.g.) `geom_` functions, but I think the underscore makes it more clear.

**Comment by hadley** [comment]
Oh I meant functions that already containing an underscore maybe don't need a `*`; i.e. `geom_` functions vs `is.*` functions?

**Comment by hadley** [comment]
Maybe it's better to always include the `*` wildcard?

**Comment by lindbrook** [comment]
I agree. It stands out better and it's _a_ standard.

**Pull request merged**
