### PR TITLE
First edition

### PR DESCRIPTION
**Pull request by eliocamp**

### CODE REVIEW

**Comment by hadley** [comment]
Can you please not check in the generated site?

**Comment by eliocamp** [comment]
Removing the `_book` folder would be ok?

**Comment by hadley** [comment]
Yeah, exactly

**Comment by eliocamp** [comment]
There it is :=

**Comment by hadley** [comment]
Oh, and `book` too

**Comment by eliocamp** [comment]
Sorry! I'm not familiar with the file structure and didn't want to delete anything important.

**Comment by hadley** [comment]
No, it's my fault — I should've been more clear about exactly what I wanted. I've now merged it by hand, so I have a clean copy of all your changes. Thanks again!

**Pull request closed without merging**
