### PR TITLE
Update Environments.Rmd

### PR DESCRIPTION
**Pull request by stephens999**
these looked like a typo to me?
fyi the "edit this page" button didn't work - it said page not found

### CODE REVIEW

**Comment by dpshelio** [comment]
I've found that typo too! - Thanks @stephens999 for fixing it!
It seems Travis built is failing by the same problem that the [master branch failed around that time](https://travis-ci.org/hadley/adv-r/builds/197322531). If @stephens999 rebase this or the travis run gets executed again probably will make travis happy.

**Comment by stephens999** [comment]
@dpshelio  not sure what i need to do to get this pulled in... how do i "rebase"

**Comment by dpshelio** [comment]
@stephens999 you could do the following:
```sh
git remote -v # check which remotes you have set up. If you don't have one as upstream then set it up as:
git remote add upstream https://github.com/hadley/adv-r.git
git fetch upstream
git checkout patch-4 # so you are in the same branch where you make this changes
git rebase upstream/master
git push origin patch-4 # to update this PR
```
In [this post](https://robots.thoughtbot.com/keeping-a-github-fork-updated) you can get a more detailed explanation.

**Comment by stephens999** [comment]
I give up - i tried. it's two lines and it seems easier for @hadley to just make those changes
if he agrees with them.

**Pull request closed without merging**
