### PR TITLE
S4.Rmd

### PR DESCRIPTION
**Pull request by setempler**
Updated first subchapter (as in prior PR #545).

Please do not merge yet, PR sent for information reason.

More to come soon.

### CODE REVIEW

**Comment by setempler** [comment]
* [ ] Need to include copyright note.

**Comment by hadley** [comment]
Is this ready to merge? I'm going to rework the whole chapter in the near future, so it doesn't matter if it's not perfect.

**Comment by setempler** [comment]
This is the first part ready to be merged, if you would like to start immediately.

I planned to add the second part tomorrow, can leave you a note then.

**Comment by hadley** [comment]
I probably won't work on it again until Monday, so I can merge then.

**Comment by setempler** [comment]
Up to date as in previous try.

For any help desired in reviewing a new version/rewrite, let me know.

**Comment by hadley** [comment]
Thanks. For future reference, there's no need to include the copyright transfer in the source. Just a note in the PR is fine.

**Pull request merged**
