### PR TITLE
what is ".y."

### PR DESCRIPTION
**Pull request by xiaochi-liu**
Actually, I don't quite understand this part: .x and .y. for two argument functions, and ..1, ..2, ..3, etc, for functions with an arbitrary number of arguments.

### CODE REVIEW

**Comment by hadley** [comment]
Thanks, that was just a typo.

**Comment by xiaochi-liu** [comment]
Hello Hadley,

May I ask a question about this sentence in the section of "9.2.2 Anonymous functions and shortcuts":

>  The function arguments look a little quirky but allow you to refer to `.` for one argument functions, `.x` and `.y` for two argument functions, and `..1`, `..2`, `..3`, etc, for functions with an arbitrary number of arguments.

Does it mean when I define an inline anonymous function in `map()`, if the anonymous function has: 

- 1 argument: I can use `.` or `.x`;
- 2 arguments: I can use `.x` and `.y`;
- 3 arguments and above: perhaps instead of the inline anonymous function, I should use an independent function definition?

If so, what's the meaning of `..1`, `..2`, `..3`, etc, for functions with an arbitrary number of arguments? Could you please provide an example?

Many thanks for your guidance!

**Comment by hadley** [comment]
I think it's easiest to see by looking at what `as_function()` does:

``` r
rlang::as_function(~ 1)
#> <lambda>
#> function (..., .x = ..1, .y = ..2, . = ..1) 
#> 1
#> attr(,"class")
#> [1] "rlang_lambda_function" "function"
```

<sup>Created on 2020-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Then `..1`, `..2` etc are just the standard (if esoteric) R syntax for accessing specific elements of `...`.

**Comment by xiaochi-liu** [comment]
Ok, get it. Thank you very much, Hadley.

**Pull request merged**
