### PR TITLE
Add section on active fields

### PR DESCRIPTION
**Pull request by thomasp85**
This PR adds a section on active fields, when and how to use them

### CODE REVIEW

**Comment by hadley** [comment]
Thanks! I'll probably tweak it a little to be shorter, but it's a great start.

**Comment by thomasp85** [comment]
Tweak away🙂

**Comment by thomasp85** [comment]
I've been meaning to write a bit on deep cloning, but can't seem to find the right place to put it as cloning is mainly just discussed in passing - any preferences?

**Comment by hadley** [comment]
Maybe a new (brief) section on cloning somewhere? Maybe under reference semantics?

**Pull request merged**
